---
openapi: 3.1.0
info:
  title: RO-Crate API
  version: 1.0.0-SNAPSHOT
  description: >
    Open Research Data | Measure 2 | API 01<br><br>
    Interoperability between Electronic Laboratory Notebooks and Data Repositories is implemented using <a href="https://www.researchobject.org/ro-crate/"> RO-Crate</a>.<br><br>
    ⚠️ The schemas provided do not reflect the exact structure of the RO-Crate. The JSON-LD docuement should be flattened.

tags:
- name: ro-crate

paths:
  /api/v1/ro-crate:
    post:
      tags:
      - ro-crate
      requestBody:
        content:
          application/ld+json:
            schema:
              type: object
              properties:
                "@context":
                  type:
                    - string
                    - array
                    - object
                    - "null"
                "@graph":
                  type: array
                  minItems: 2
                  items:
                    oneOf:
                      - $ref: "#/components/schemas/RoCrateMetadata"
                      - $ref: "#/components/schemas/RootDataset"
                      - $ref: "#/components/schemas/Publication"
                      - $ref: "#/components/schemas/JsonLDEntity"
              required:
                - "@context"
                - "@graph"
          application/zip:
            schema:
              type: string
              format: binary
      responses:
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "422":
          description: Unacceptable content
        "500":
          description: Internal server error
      summary: Import RO Crate
  /api/v1/ro-crate/publications/{doi}:
    get:
      tags:
      - ro-crate
      parameters:
      - name: doi
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/ld+json:
              schema:
                $ref: "#/components/schemas/RoCrate"
            application/zip:
              schema:
                type: string
                format: binary
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not found
        "422":
          description: Unacceptable content
        "500":
          description: Internal server error
      summary: Export a Publication from a DOI to a RO-Crate

# https://github.com/json-ld/json-ld.org/blob/main/schemas/jsonld-schema.json
components:
  schemas:
    RoCrate:
      type: object
      properties:
        "@context":
          type:
            - string
            - array
            - object
            - "null"
        "@graph":
          type: array
          minItems: 2
          items:
            oneOf:
              - $ref: "#/components/schemas/RoCrateMetadata"
              - $ref: "#/components/schemas/RootDataset"
              - $ref: "#/components/schemas/JsonLDEntity"

    RoCrateMetadata:
      type: object
      additionalProperties: true
      properties:
        "@type":
          type: string
          const: "CreativeWork"
        "@id":
          type: string
          const: "ro-crate-metadata.json"
        conformsTo:
          type: object
          properties:
            "@id":
              type: string
              const: "https://w3id.org/ro/crate/1.1"
        about:
          type: object
          properties:
            "@id":
              type: string
              const: "./"
      required:
        - "@type"
        - "@id"
        - conformsTo
        - about

    RootDataset:
      type: object
      additionalProperties: true
      properties:
        "@type":
          type: string
          enum: 
          - "Dataset"
        "@id":
          type: string
          enum: 
          - "./"
        name:
          type: string
        description:
          type: string
        datePublished:
          type: string
          format: date-time
        license:
          type: object
      required:
        - "@type"
        - "@id"
        - name
        - description
        - datePublished
        - license

    Dataset:
      type: object
      additionalProperties: true
      properties:
        "@type":
          type: string
          const: "Dataset"
        "@id":
          type: string
        name:
          type: string
        dateCreated:
          type: string
          format: date-time
      requiredProperties:
        - "@id"
        - "@type"
        - name
        - dateCreated

    Publication:
      type: object
      additionalProperties: true
      properties:
        "@type":
          type: string
          const: "CreativeWork"
        "@id":
          type: string
        identifer:
          type: string
        title:
          type: string
        publisher:
          affiliation: 
          $ref: "#/components/schemas/Organization"
        datePublished:
          type: string
          format: date-time
        creator:
          type: array
          items:
            $ref: "#/components/schemas/Person"
        license:
          type: object
          properties:
            "@id":
              type: string
          requiredProperties:
            - "@id"
        description:
          type: string
      requiredProperties:
        - "@id"
        - "@type"
        - identifier
        - title
        - publisher
        - datePublished
        - creator
        - description
        - license

    Person:
      type: object
      additionalProperties: true
      properties:
        "@type":
          type: string
        "@id":
          type: string
        name: 
          type: string
        givenName: 
          type: string
        familyName: 
          type: string
        affiliation: 
          $ref: "#/components/schemas/Organization"
      required:
        - "@type"
        - "@id"
        - name
        - givenName
        - familyName

    Organization:
      type: object
      additionalProperties: true
      properties:
        "@type":
          type: string
          const: "Organization"
        "@id":
          type: string
        name:
          type: string
        url:
          type: string
      required:
        - "@type"
        - "@id"
        - name

    JsonLDEntity:
      type: object
      additionalProperties: true
      properties:
        "@type":
          type: string
        "@id":
          type: string
      required:
        - "@type"
        - "@id"