name: CI

on:
  pull_request:
    branches: '**'

permissions:
  packages: write

env:
  devImage: ghcr.io/${{ github.repository }}-devcontainer
  mavenCacheVolume: devcontainer-maven-cache-${{ github.event.repository.name }}

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      rebuildDevContainer: ${{ steps.check_changes.outputs.devcontainer_any_changed }}
      rebuildMavenCache: ${{ steps.check_changes.outputs.deps_any_changed }}
      lintWorkflows: ${{ steps.check_changes.outputs.workflow_any_changed }}
      runTests: ${{ steps.check_changes.outputs.src_any_changed }}
    steps:
      - uses: actions/checkout@v7
      - name: Check for changes
        id: check_changes
        uses: tj-actions/changed-files@v47
        with:
          files_yaml: |
            devcontainer:
              - .devcontainer/**
            deps:
              - pom.xml
            workflow:
              - .github/workflows/**
            src:
              - src/**
              - pom.xml
              - .github/workflows/ci.yaml
              - .mvn/**
              - mvnw{,.cmd}
              - .devcontainer/**

  build:
    runs-on: ubuntu-latest
    needs: check_changes
    if: needs.check_changes.outputs.rebuildDevContainer == 'true'
    steps:
      - uses: actions/checkout@v7

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.devImage }}
          cacheFrom: ${{ env.devImage }}
          push: always

  maven_cache:
    name: Build Maven cache
    needs: check_changes
    if: needs.check_changes.outputs.rebuildMavenCache == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Restore Maven cache volume
        id: restore_maven_cache
        uses: BYK/docker-volume-cache-action/restore@0efa5cf5178c9906cb46ed8d1a357df8fd6b1a06 # v1
        with:
          key: maven-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-m2-
          volumes: ${{ env.mavenCacheVolume }}

      - name: Download Maven dependencies
        uses: devcontainers/ci@v0.3
        with:
          push: never
          imageName: ${{ env.devImage }}
          cacheFrom: ${{ env.devImage }}
          runCmd: ./mvnw dependency:go-offline

      - name: Save Maven cache volume
        uses: BYK/docker-volume-cache-action/save@0efa5cf5178c9906cb46ed8d1a357df8fd6b1a06 # v1
        with:
          key: ${{ steps.restore_maven_cache.outputs.cache-primary-key }}
          volumes: ${{ env.mavenCacheVolume }}

  tests:
    name: Unit + Integration tests
    needs: [check_changes, maven_cache]
    if: needs.check_changes.outputs.runTests == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Restore Maven cache volume
        uses: BYK/docker-volume-cache-action/restore@0efa5cf5178c9906cb46ed8d1a357df8fd6b1a06 # v1
        with:
          key: maven-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-m2-
          volumes: ${{ env.mavenCacheVolume }}

      - name: Run test suite
        uses: devcontainers/ci@v0.3
        with:
          push: never
          imageName: ${{ env.devImage }}
          cacheFrom: ${{ env.devImage }}
          runCmd: ./mvnw verify -DskipITs=false

  actionlint:
    runs-on: ubuntu-latest
    needs: check_changes
    if: needs.check_changes.outputs.lintWorkflows == 'true'
    steps:
      - uses: actions/checkout@v7
      - name: Lint workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color

  precommit:
    name: pre-commit
    needs: maven_cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Restore Maven cache volume
        uses: BYK/docker-volume-cache-action/restore@0efa5cf5178c9906cb46ed8d1a357df8fd6b1a06 # v1
        with:
          key: maven-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-m2-
          volumes: ${{ env.mavenCacheVolume }}

      - name: pre-commit
        uses: devcontainers/ci@v0.3
        with:
          push: never
          imageName: ${{ env.devImage }}
          cacheFrom: ${{ env.devImage }}
          runCmd: pre-commit run --all-files
