name: Release

on:
  push:
    branches:
      - main

env:
  devImage: ghcr.io/${{ github.repository }}-devcontainer

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }} # Allows to bypass branch protection
          fetch-depth: 0
      - name: Release
        uses: devcontainers/ci@v0.3
        with:
          push: never
          imageName: ${{ env.devImage }}
          cacheFrom: ${{ env.devImage }}
          runCmd: |
            docker login ghcr.io -u $GITHUB_ACTOR --password $GITHUB_TOKEN \
            && echo ${DEPLOY_KEY} > /tmp/deploy_key                        \
            && eval $(ssh-agent -s)                                        \
            && ssh-add /tmp/deploy_key                                     \
            && npm install --prefix .github/semantic-release               \
            && npx --prefix .github/semantic-release semantic-release
          env: |
            CI=true
            DEPLOY_KEY=${{ secrets.DEPLOY_KEY}}
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            GITHUB_ACTION=${{ github.action }}
            GITHUB_ACTOR=${{ github.actor }}
            GITHUB_REPOSITORY=${{ github.repository }}
            GITHUB_REF=${{ github.ref }}
            GITHUB_SHA=${{ github.sha }}
            GITHUB_WORKFLOW=${{ github.workflow }}
            GITHUB_RUN_ID=${{ github.run_id }}
            GITHUB_RUN_NUMBER=${{ github.run_number }}
